language: php

php:
  - 7.3

env:
  - CONTAINER=frontend
  - CONTAINER=backend
  - CONTAINER=worker-feed
  - CONTAINER=worker-images
  - CONTAINER=worker-solr
  - CONTAINER=worker-stats

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - composer global require -q hirak/prestissimo

before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - composer install

script:
  - make build SERVICE=$CONTAINER

after_script:
  - make push SERVICE=$CONTAINER

notifications:
  email:
    - matthew@baggett.me
