language: php

php:
  - 7.3

env:
  - DOCKER_COMPOSE_VERSION=1.21.0
  - CONTAINER=frontend
  - CONTAINER=backend
  - CONTAINER=worker-feed

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - composer global require -q hirak/prestissimo

script:
  - composer install
  - docker-compose build $CONTAINER

before_deploy:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD $DOCKER_REGISTRY
  - docker-compose push $CONTAINER

notifications:
  email:
    - matthew@baggett.me
