version: '2.4'

services:
  frontend:
    cpus: 0.50
    scale: 2

  backend:
    cpus: 0.50
    scale: 2

  worker-feed:
    environment:
      THREAD_MULTIPLE: 0.50
      DELAY_PER_ITEM_MS: 250
    cpus: 0.20

  worker-images:
    cpus: 0.20

  worker-solr:
    cpus: 0.40

  redis:
    volumes:
      - persist-redis:/data
    cpus: 0.70

  solr:
    volumes:
      - persist-solr:/opt/solr/server/solr/mycores
    cpus: 0.30

volumes:
  persist-solr:
  persist-redis: