version: '2.4'

networks:
  private:

services:
  worker-feed:
    build:
      context: .
      target: worker-feed
    image: baaz/worker-feed
    restart: always
    volumes:
      - ./:/app
    networks:
      - private
    depends_on:
      redis-backend:
        condition: service_healthy
    environment:
      REDIS_HOST: tcp://redis-backend:6379
      THREAD_MULTIPLE: 0.25
      DELAY_PER_ITEM_MS: 0

  worker-images:
    build:
      context: .
      target: worker-images
    image: baaz/worker-images
    restart: always
    volumes:
      - ./:/app
    networks:
      - private
    depends_on:
      redis-backend:
        condition: service_healthy
    environment:
      REDIS_HOST: tcp://redis-backend:6379

  worker-solr:
    build:
      context: .
      target: worker-solr
    image: baaz/worker-solr
    restart: always
    volumes:
      - ./:/app
    networks:
      - private
    depends_on:
      redis-backend:
        condition: service_healthy
      solr:
        condition: service_started
    environment:
      REDIS_HOST: tcp://redis-backend:6379
      SOLR_HOST: tcp://solr:8983
