version: '2.4'

networks:
  public:
    name: baaz_public
  private:

services:

  redis:
    image: redis:5
    restart: always
    ports:
      - 127.0.0.20:6379:6379
    command: redis-server --appendonly yes
    networks:
      - private
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  solr:
    image: solr
    restart: always
    ports:
      - "127.0.0.20:8983:8983"
    volumes:
      - ./solr:/baaz
    networks:
      - public
      - private
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - baaz
    labels:
      - "traefik.docker.backend=solr"
      - "traefik.port=8983"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.rule=Host:solr.baaz.local"
      - "traefik.docker.network=baaz_public"
